### ISSUE TITLE
AOT Compilation failed in ng2-truncate/dist/index.d.ts version 1.2.0

### ISSUE THREAD

**Issue by budcribar** [yellowspot/ng2-truncate#14]
C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot>"node_modules/.bin/ngc" -p tsconfig-aot.json
Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 2:22 in the original .ts file), resolving symbol TRUNCATE_PIPES in C:/Users/budcr/Source/Workspaces/CloudForestWebSite/CloudForest/wwwroot/node_modules/ng2-truncate/dist/index.d.ts, resolving symbol AppModule in C:/Users/budcr/Source/Workspaces/CloudForestWebSite/CloudForest/wwwroot/app/app.module.ts, resolving symbol AppModule in C:/Users/budcr/Source/Workspaces/CloudForestWebSite/CloudForest/wwwroot/app/app.module.ts
    at positionalError (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25894:37)
    at simplifyInContext (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25731:29)
    at StaticReflector.simplify (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25745:15)
    at StaticReflector.annotations (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25243:62)
    at NgModuleResolver.resolve (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:17584:84)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:18092:62)
    at addNgModule (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25005:60)
    at C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25016:16
    at Array.forEach (native)
    at _createNgModules (C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\compiler\bundles\compiler.umd.js:25015:28)
Compilation failed

**Comment by mgrunberg** [comment]
We are working on this in #13
