### ISSUE TITLE
Problem with loading module

### ISSUE THREAD

**Issue by dmitrofanov777** [yellowspot/ng2-truncate#21]
After upgrading to Angular 4.0 I have this error: 
ERROR Error: Uncaught (in promise): Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:366:26)
	    at Object.onInvoke (http://localhost:3000/assets/@angular/core/bundles/core.umd.js:4133:37)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:365:32)
	    at Zone.run (http://localhost:3000/assets/zone.js/dist/zone.js:126:43)
	Evaluating http://localhost:3000/traceur
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/assets/ng2-truncate/dist/index.js
	Error loading http://localhost:3000/assets/ng2-truncate/dist/index.js as "ng2-truncate" from http://localhost:3000/assets/angular/base/organizer/organizer.module.js
(SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:366:26)
	    at Object.onInvoke (http://localhost:3000/assets/@angular/core/bundles/core.umd.js:4133:37)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:365:32)
	    at Zone.run (http://localhost:3000/assets/zone.js/dist/zone.js:126:43)
	Evaluating http://localhost:3000/traceur
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/assets/ng2-truncate/dist/index.js
	Error loading http://localhost:3000/assets/ng2-truncate/dist/index.js as "ng2-truncate" from http://localhost:3000/assets/angular/base/organizer/organizer.module.js
	    at eval (<anonymous>)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:366:26)
	    at Object.onInvoke (http://localhost:3000/assets/@angular/core/bundles/core.umd.js:4133:37)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:365:32)
	    at Zone.run (http://localhost:3000/assets/zone.js/dist/zone.js:126:43)
	Evaluating http://localhost:3000/traceur
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/assets/ng2-truncate/dist/index.js
	Error loading http://localhost:3000/assets/ng2-truncate/dist/index.js as "ng2-truncate" from http://localhost:3000/assets/angular/base/organizer/organizer.module.js
(SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:366:26)
	    at Object.onInvoke (http://localhost:3000/assets/@angular/core/bundles/core.umd.js:4133:37)
	    at ZoneDelegate.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:365:32)
	    at Zone.run (http://localhost:3000/assets/zone.js/dist/zone.js:126:43)
	Evaluating http://localhost:3000/traceur
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/assets/ng2-truncate/dist/index.js
	Error loading http://localhost:3000/assets/ng2-truncate/dist/index.js as "ng2-truncate" from http://localhost:3000/assets/angular/base/organizer/organizer.module.js
    at resolvePromise (http://localhost:3000/assets/zone.js/dist/zone.js:713:31) [angular]
    at resolvePromise (http://localhost:3000/assets/zone.js/dist/zone.js:684:17) [angular]
    at http://localhost:3000/assets/zone.js/dist/zone.js:761:17 [angular]
    at Object.onInvokeTask (http://localhost:3000/assets/@angular/core/bundles/core.umd.js:4124:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:3000/assets/zone.js/dist/zone.js:398:36) [angular]
    at Zone.runTask (http://localhost:3000/assets/zone.js/dist/zone.js:166:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:3000/assets/zone.js/dist/zone.js:594:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/assets/zone.js/dist/zone.js:465:25) [<root>]

ng2-truncate is loaded with systemjs like this:
System.config({
        map: {
            ......
            'ng2-truncate': '/assets/ng2-truncate/dist',
            .......
        },
        packages: {
           .......
            'ng2-truncate': {main: 'index', defaultExtension: 'js'},
            .......
        }
    });
also tried
System.config({
        map: {
            ......
            'ng2-truncate': '/assets/ng2-truncate',
            .......
        },
        packages: {
           .......
            'ng2-truncate': {main: 'dist/index', defaultExtension: 'js'},
            .......
        }
    });
What is wrong?

**Comment by cristianstu** [comment]
Probably the path (` '/assets/ng2-truncate/dist'`) is wrong or the folder has a wrong content.

Check this plunker working with systemjs https://embed.plnkr.co/d3JiQCw756OEjS0HkVuY

You can try to point to the npm cdn to check if it is a local path resolution issue
```js
map: {
   'ng2-truncate': 'https://npmcdn.com/ng2-truncate/dist'
}
```

**Comment by dmitrofanov777** [comment]
I understand this. This path: '/assets/ng2-truncate/dist' is just a mapping to node_modules folder. No i downgraded to angular 2.4.8 and ng-truncate 1.2.0, and everything works well with the same settings

**Comment by cristianstu** [comment]
I think this is related to the environment and not this package.

**Comment by OElabed** [comment]
@cristianstu I have the same error when i install ng2-truncate 1.3.5 with Angular 4.0.0 .

I use System JS like  module loader:

`name: 'ng2-truncate',
      packageMeta: {
        main: 'dist/index.js',
        defaultExtension: 'js'
      }
`
