### ISSUE TITLE
Calling function 'ɵmakeDecorator', function calls are not supported

### ISSUE THREAD

**Issue by filippodicostanzo** [yellowspot/ng2-truncate#26]
This is an error when i try to build a ios --prod with ionic.

This is the error:

`Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/ng2-truncate/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/ng2-truncate/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/ng2-truncate/node_modules/@angular/core/core.d.ts
    at Error (native)
    at syntaxError (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
    at simplifyInContext (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:23870:23)
    at StaticReflector.simplify (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:13)
    at StaticReflector.annotations (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:23331:41)
    at NgModuleResolver.resolve (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:13883:70)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:14473:60)
    at addNgModule (/Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:23050:58)
    at /Users/filippodicostanzo/Desktop/IonicProjects/CinemaIris2.1/node_modules/@angular/compiler/bundles/compiler.umd.js:23061:14
    at Array.forEach (native)`

Any solution?

No issue with 1.3.7 version!

**Comment by mgrunberg** [comment]
Can you tell which version of angular are you using?

**Comment by filippodicostanzo** [comment]
`        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",`

**Comment by mgrunberg** [comment]
Please try with version `1.3.11-alpha.1` and let me know what happened

**Comment by filippodicostanzo** [comment]
@mgrunberg yes!

now it work perfectly!

Thank you for your time :)

**Comment by mgrunberg** [comment]
You are welcome. You can use the final version: `1.3.11`
