### ISSUE TITLE
Jest error

### ISSUE THREAD

**Issue by tibistibi** [yellowspot/ng2-truncate#38]
After adding this module to my applications a got an error from jest:

```

         Jest encountered an unexpected token

         This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

         By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

         Here's what you can do:
          • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
          • If you need a custom transformation specify a "transform" option in your config.
          • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

         You'll find more details and examples of these config options in the docs:
         https://jestjs.io/docs/en/configuration.html

         Details:

         /home/tibi/git/standBystand/node_modules/@yellowspot/ng-truncate/dist/index.js:1
         ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { TruncateModule, TRUNCATE_PIPES } from './truncate.module';
                                                                                                  ^^^^^^

         SyntaxError: Unexpected token export



           at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
           at Object.<anonymous> (src/main/webapp/app/shared/shared.module.ts:279:72)```

**Comment by mgrunberg** [comment]
From the error path I can tell that you are using version 1.4.0. Can you try with the leatest version (1.5.1)?
